
kind: Service
apiVersion: v1
metadata:
  name: kafka-producer-processor
spec:
  selector:
    app: kafka-producer-processor
  type: NodePort
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 31001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-processor
  labels:
    app: kafka-producer-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-processor
  template:
    metadata:
      labels:
        app:kafka-producer-processor
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: maven
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 31001