spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      replication-factor: ${KAFKA_REPLICATION_FACTOR}
      num-partition: ${KAFKA_NUM_PARTITION}
    producer:
      acks: all
      retries: 100
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${KAFKA_REGISTRY_URL}
        specific.avro.reader: true
      template:
        default-topic: test
logging:
  level:
    org.springframework: ${LOG_LEVEL}
    com.cmcglobal.kafkstreamprocessor: ${LOG_LEVEL}
sentry:
  dsn: ${SENTRY_DNS}
  traces-sample-rate: 1.0
  environment: ${SENTRY_ENV}
debug: ${DEBUG}
server:
  port: 7001