spring:
  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    bootstrap-servers: localhost:9092
    topic:
#      replication-factor: ${KAFKA_REPLICATION_FACTOR}
#      num-partition: ${KAFKA_NUM_PARTITION}
      replication-factor: 1
      num-partition: 3
    producer:
      acks: all
      retries: 100
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
      template:
        default-topic: test
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 30
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
  batch:
    initialize-schema: always
logging:
  level:
    org.springframework: ${LOG_LEVEL}
    com.cmcglobal.kafkstreamprocessor: ${LOG_LEVEL}
sentry:
  dsn: ${SENTRY_DNS}
  traces-sample-rate: 1.0
  environment: ${SENTRY_ENV}
debug: ${DEBUG}
server:
  port: 7001
