# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
    - name: Build & Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: chjplove/kafka-producer-processor
        tags: latest
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Deploy the package to the remote server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /app/target/kafka-producer-processor.jar
        remote: kafka-producer-processor.jar
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
    - name: Run a script on remote server (start the application)
      if: always()
      uses: fifsky/ssh-action@master
      with:
        script: |
          docker stop kafka-producer-processor
          && docker container rm kafka-producer-processor
          && docker image rm chjplove/kafka-producer-processor
          && docker pull chjplove/kafka-producer-processor:latest
          && docker run -p 7001:7001 --name kafka-producer-processor -d chjplove/kafka-producer-processor:latest
        host: ${{ secrets.HOST }}
        user: ${{ secrets.SSH_USER }}
        pass: ${{ secrets.SSH_PASSWORD }}
        args: "-tt"

      
